# Redirect with a 301
[[redirects]]
from = "/ru"
to = "/"
status = 301

[[redirects]]
from = "/ru/portfolio"
to = "/portfolio"
status = 301

[[redirects]]
from = "/ru/faq"
to = "/faq"
status = 301

[[redirects]]
from = "/ru/about"
to = "/about"
status = 301

[[redirects]]
from = "/ru/our-values"
to = "/our-values"
status = 301

[[redirects]]
from = "/ru/reviews"
to = "/reviews"
status = 301

# Редирект для головної сторінки з багатьма слешами
[[redirects]]
  from = "//+"
  to = "/"
  status = 301
  force = true

# Редирект для інших сторінок із багатьма слешами
[[redirects]]
  from = "/:splat"
  to = "/:splat"
  status = 301
  force = true
  conditions = { path = "^/(.+//.*)$" }

